analytics: {}
color:
  brandColors:
    - '#B8A070'
    - '#106880'
    - '#807048'
    - '#D04008'
    - '#D8C8A0'
  brandStrength: 0.647804
  lightness: 0.510978
  rhythmicContrast: 0.756756
  saturation: 0.500843
cta: {}
layout_spectrum: 1
name: lifeisrandom
opengraph: {}
purpose: {}
typography_spectrum: 1
