analytics: {}
color:
  brandColors:
    - '#B8A070'
    - '#106880'
    - '#807048'
    - '#D04008'
    - '#D8C8A0'
  brandStrength: 0.334459
  lightness: 0.016047
  rhythmicContrast: 0.499155
  saturation: 0.506756
cta: {}
layout_spectrum: 0.200168
name: lifeisrandom
opengraph: {}
purpose: {}
typography_spectrum: 1
