analytics: {}
color:
  brandColors:
    - '#B8A070'
    - '#106880'
    - '#807048'
    - '#D04008'
    - '#D8C8A0'
  brandStrength: 1
  lightness: 0.510979
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 1
name: lifeisrandom
opengraph: {}
purpose: {}
typography_spectrum: 1
