analytics: {}
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.334459
  lightness: 0.499155
  rhythmicContrast: 0.499155
  saturation: 0.506756
cta: {}
layout_spectrum: 0.200168
name: lifeisrandom
opengraph: {}
purpose: {}
typography_spectrum: 1
